# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TIL
email: lebinh.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My yada nada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lebinh.github.io" # the base hostname & protocol for your site
twitter_username: lebinh
github_username:  lebinh

# Build settings
markdown: kramdown
